# Generated by Django 4.2 on 2026-03-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='管理员账号')),
                ('password', models.CharField(max_length=50, verbose_name='管理员密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=2, verbose_name='性别')),
                ('dept', models.CharField(max_length=50, verbose_name='所属院系')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('grade', models.CharField(max_length=10, verbose_name='年级')),
                ('clazz', models.CharField(max_length=20, verbose_name='班级')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系方式')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'ordering': ['-add_time'],
            },
        ),
    ]
