# Generated by Django 4.2 on 2026-03-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('sno', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='学号')),
                ('password', models.CharField(max_length=50, verbose_name='登录密码')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生账号',
                'verbose_name_plural': '学生账号',
            },
        ),
    ]
