# Generated by Django 4.2 on 2026-04-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_studentuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='app.student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'ordering': ['subject'],
                'constraints': [models.UniqueConstraint(fields=('student', 'subject'), name='unique_student_subject_score')],
            },
        ),
    ]
